### ISSUE TITLE
Can't resume playback if the last song in the queue finishes

### ISSUE THREAD

**Issue by farktronix** [alecgorge/gapless-audio-bass-ios#8]
If you play the last track in the queue and let it play to completion then it's not possible to replay that track again either by hitting the play/pause button, seeking in the track, or tapping on the track in the queue again.
As soon as another track is played the last track will play again.

**Comment by alecgorge** [comment]
This sounds like an edge case in the BASS end callback switch code. There
is a lot of logic there to try to reuse things.

I can actually look at this in about 8 hours if you can’t get to it

**Comment by farktronix** [comment]
Yep, I'm pretty sure this has to do with something keeping state about what URL is currently playing. I took a quick look but I don't think I'll have time to get to the bottom of this any time soon, so I filed this issue to track it. Feel free to take a shot at it if you have some free time!
